# Generated by cpp11: do not edit by hand

dust2_system_cows_alloc <- function(r_pars, r_time, r_dt, r_n_particles, r_n_groups, r_seed, r_deterministic) {
  .Call(`_cowflu_dust2_system_cows_alloc`, r_pars, r_time, r_dt, r_n_particles, r_n_groups, r_seed, r_deterministic)
}

dust2_system_cows_run_to_time <- function(ptr, r_time) {
  .Call(`_cowflu_dust2_system_cows_run_to_time`, ptr, r_time)
}

dust2_system_cows_state <- function(ptr, grouped) {
  .Call(`_cowflu_dust2_system_cows_state`, ptr, grouped)
}

dust2_system_cows_time <- function(ptr) {
  .Call(`_cowflu_dust2_system_cows_time`, ptr)
}

dust2_system_cows_set_state_initial <- function(ptr) {
  .Call(`_cowflu_dust2_system_cows_set_state_initial`, ptr)
}

dust2_system_cows_set_state <- function(ptr, r_state, grouped) {
  .Call(`_cowflu_dust2_system_cows_set_state`, ptr, r_state, grouped)
}

dust2_system_cows_reorder <- function(ptr, r_index) {
  .Call(`_cowflu_dust2_system_cows_reorder`, ptr, r_index)
}

dust2_system_cows_rng_state <- function(ptr) {
  .Call(`_cowflu_dust2_system_cows_rng_state`, ptr)
}

dust2_system_cows_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_cowflu_dust2_system_cows_set_rng_state`, ptr, r_rng_state)
}

dust2_system_cows_set_time <- function(ptr, r_time) {
  .Call(`_cowflu_dust2_system_cows_set_time`, ptr, r_time)
}

dust2_system_cows_update_pars <- function(ptr, pars, grouped) {
  .Call(`_cowflu_dust2_system_cows_update_pars`, ptr, pars, grouped)
}

dust2_system_cows_simulate <- function(ptr, r_times, r_index, grouped) {
  .Call(`_cowflu_dust2_system_cows_simulate`, ptr, r_times, r_index, grouped)
}
