## Generated by dust2 (version 0.3.11) - do not edit
cows <- structure(
  function() get("cows"),
  class = "dust_system_generator",
  name = "cows",
  package = "cowflu",
  path = NULL,
  parameters = NULL,
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = 1)
