## Generated by dust2 (version 0.2.1) - do not edit
cows <- structure(
  function() get("cows"),
  class = "dust_system_generator",
  name = "cows",
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = 1)
